[general]
import = []
working_directory = "~/ranger097_nixos_dotfiles"

[window]
padding = { x = 20, y = 20 }
opacity = 0.6
startup_mode = "Windowed"

[font]
normal = { family = "Victor Mono NF", style = "Regular" }
bold = { family = "Victor Mono NF", style = "Bold" }
italic = { family = "Victor Mono NF", style = "SemiBold Italic" }
offset = { x = 0, y = 30 }
size = 14.0

[colors]
transparent_background_colors = true 
