[general]
import = []
working_directory = "None"

[window]
padding = { x = 10, y = 10 }
opacity = 0.5
startup_mode = "Windowed"

[font]
normal = { family = "Victor Mono NF", style = "Regular" }
bold = { family = "Victor Mono NF", style = "Bold" }
italic = { family = "Victor Mono NF", style = "Bold Italic" }
size = 14.0
[colors]
transparent_background_colors = true
