[general]
import = []
working_directory = "~/ranger097_nixos_dotfiles"

[window]
padding = { x = 25, y = 25 }
opacity = 1.0
startup_mode = "Windowed"

[font]
#normal = { family = "Victor Mono NF", style = "Regular" }
#bold = { family = "Victor Mono NF", style = "Bold" }
#italic = { family = "Victor Mono NF", style = "SemiBold Italic" }

#normal = { family = "Maple Mono NF CN", style = "Light" }
#bold = { family = "Maple Mono NF CN", style = "Bold" }
#italic = { family = "Maple Mono NF CN", style = "Bold Italic" }

#normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#bold = { family = "JetBrainsMono Nerd Font", style = "Light" }
#italic = { family = "JetBrainsMono Nerd Font", style = "Bold" }

#normal = { family = "GeistMono NFM", style = "medium" }
#bold = { family = "GeistMono NFM", style = "Black" }
#italic = { family = "GeistMono NFM", style = "SemiBold" }

#normal = { family = "AdwaitaMono Nerd Font", style = "Regular" }
#bold = { family = "AdwaitaMono Nerd Font", style = "Bold" }
#italic = { family = "AdwaitaMono Nerd Font", style = "Italic" }

#normal = { family = "ZedMono NF", style = "Regular" }
#bold = { family = "ZedMono NF", style = "Bold" }
#italic = { family = "ZedMono NF", style = "Italic" }

normal = { family = "CaskaydiaCove NF", style = "Light" }
bold = { family = "CaskaydiaCove NF", style = "Bold" }
italic = { family = "CaskaydiaCove NFP", style = "Italic" }

offset = { x = 0, y = 15 }
size = 14.0

[colors]
transparent_background_colors = true

[colors.primary]
background = '#000000'
foreground = "#DCD7BA"

[colors.normal]
black   = "#54546D" #\[\e[0;30m\] Muted Navy/Grey
red     = "#FF5D62" #\[\e[0;31m\] Soft Coral Red
green   = "#98BB6C" #\[\e[0;32m\] Sage Green
yellow  = "#DCD7BA" #\[\e[0;33m\] Sand / Beige
blue    = "#7E9CD8" #\[\e[0;34m\] Cornflower Blue
magenta = "#D27E99" #\[\e[0;35m\] Dusty  Rose
cyan    = "#727169" #\[\e[0;36m\] Warm Grey
white   = "#FFA066" #\[\e[0;37m\] Mango / Orange

[colors.bright]
black   = "#54546D" #\[\e[0;30m\] Muted Navy/Grey
red     = "#FF5D62" #\[\e[0;31m\] Soft Coral Red
green   = "#98BB6C" #\[\e[0;32m\] Sage Green
yellow  = "#DCD7BA" #\[\e[0;33m\] Sand / Beige
blue    = "#7E9CD8" #\[\e[0;34m\] Cornflower Blue
magenta = "#D27E99" #\[\e[0;35m\] Dusty Rose
cyan    = "#727169" #\[\e[0;36m\] Warm Grey
white   = "#FFA066" #\[\e[0;37m\] Mango / Orange
